### ISSUE TITLE
Entry not found

### ISSUE THREAD

**Issue by axb-c** [d3vilh/stable-diffusion-howto#1]
In the file mentioned in point 5, the 'Entry not found' message is displayed when downloading.
[https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-inference-v.yaml](https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-inference-v.yaml)

**Comment by d3vilh** [comment]
Hi @axb-c,
I updated links to `.safetensors` SD2 and SD2.1 models with instruction steps update as well.
Thank you!
